
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "The Clean Coder",
  "authorId": 2,
  "publishedAt": "2011-05-13",
  "isbn": "978-0137081073",
  "summary": "A guide to professionalism in software development from Uncle Bob.",
  "pageCount": 256,
  "language": "English",
  "genres": [1, 3]
}

